config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  root to: 'pages#index'

  # static pages
  get '/projects' => 'pages#projects', as: :projects
  get '/about' => 'pages#about', as: :about
  get '/secret', to: 'pages#secret', as: :secret

  # custom route names
  get '/makesomewords', to: 'posts#new'

  # login/logout stuff
  get "/auth/:provider/callback", to: "sessions#create"
  get "/logout" => "sessions#destroy", as: :logout

  # CRUD resources
  resources :posts

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :author, :body, :email
  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates_presence_of :title, :body
  validates_uniqueness_of :title

end

app/models/slug.rb
# Stores slugs used to prettify URLs. For more information, see the
# {Slugalicious} mixin.
#
# As new slugs are created, old ones are marked as inactive and kept around for
# redirect purposes. Once a slug is old enough, it is deleted and its value can
# be used for new records (no longer redirects).
#
# Associations
# ============
#
# |             |                                       |
# |:------------|:--------------------------------------|
# | `sluggable` | The record that this slug references. |
#
# Properties
# ==========
#
# |          |                                                                                                  |
# |:---------|:-------------------------------------------------------------------------------------------------|
# | `slug`   | The slug, lowercased and normalized. Slugs must be unique to their `sluggable_type` and `scope`. |
# | `active` | Whether this is the most recently generated slug for the sluggable.                              |
# | `scope`  | Freeform data scoping this slug to a certain subset of records within the model.                 |

class Slug < ActiveRecord::Base
  belongs_to :sluggable, polymorphic: true

  scope :for, ->(object_or_type, object_id=nil) {
    object_type = object_id ? object_or_type : object_or_type.class.to_s
    object_id ||= object_or_type.id
    where(sluggable_type: object_type, sluggable_id: object_id)
  }
  scope :for_class, ->(model) { where(sluggable_type: model.to_s) }
  scope :from_slug, ->(klass, scope, slug) {
    where(sluggable_type: klass.to_s, slug: slug, scope: scope)
  }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  validates :sluggable_type,
            presence: true
  validates :sluggable_id,
            presence: true,
            numericality: { only_integer: true }
  validates :slug,
            presence: true,
            length: { maximum: 126 },
            uniqueness: { case_sensitive: false, scope: [ :scope, :sluggable_type ] }
  validates :scope,
            length: { maximum: 126 },
            allow_nil: true
  validate :one_active_slug_per_object

  after_save :invalidate_cache
  after_destroy :invalidate_cache

  # Marks a slug as active and deactivates all other slugs assigned to the
  # record.

  def activate!
    self.class.transaction do
      Slug.for(sluggable_type, sluggable_id).update_all(active: false)
      update_column :active, true
    end
  end

  private

  def one_active_slug_per_object
    return unless new_record? or (active? and active_changed?)
    errors.add(:active, :one_per_sluggable) if active? and Slug.active.for(sluggable_type, sluggable_id).count > 0
  end

  def invalidate_cache
    Rails.cache.delete "Slug/#{sluggable_type}/#{sluggable_id}/slug"
    Rails.cache.delete "Slug/#{sluggable_type}/#{sluggable_id}/slug_with_path"
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.find_or_create_from_omniauth(auth_hash)
    user = self.find_by(uid: auth_hash["uid"], provider: auth_hash["provider"])
    if !user.nil?
      # User found, continue on with your life
      return user
    else
      # Create a new user
      user = User.new
      user.uid        = auth_hash["uid"]
      user.provider   = auth_hash["provider"]
      user.username   = auth_hash["info"]["name"]
      user.email      = auth_hash["info"]["email"]
      user.avatar_url = auth_hash["info"]["image"]
    end
    if user.save
      return user
    else
      return nil
    end
  end

  def is_riley?
    if self == User.find_by(uid: "13241167", username: "Riley Spicer")
      return true
    else
      return false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def must_be_logged_in
    if !@current_user
      flash[:error] = "Silly rabbit, Trix are for kids."
      redirect_to root_path
    end
  end

  def must_be_owner
    if @current_user != User.find_by(uid: "13241167", username: "Riley Spicer")
      flash[:error] = "Silly rabbit, Trix are for kids."
      redirect_to root_path
    end
  end

  def riley_only
    if !@current_user.is_riley?
      flash[:error] = "Silly rabbit, Trix are for kids."
      redirect_to root_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new; end

  def create
    
  end

  def edit; end

  def update; end

  def destroy; end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    render :layout => "front-page"
  end
  def about
  end
  def projects
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :must_be_owner, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    Post.create(
        title: post_params[:title],
        body: post_params[:body]
      )
    redirect_to posts_path
  end

  def edit; end

  def update
    @post.update(post_params)
    redirect_to posts_path
  end

  def destroy; end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth_hash = request.env['omniauth.auth']
    if auth_hash["uid"]
      @user = User.find_or_create_from_omniauth(auth_hash)
      if @user
        session[:user_id] = @user.id
        redirect_to root_path
      else
        redirect_to root_path, notice: "Failed to save the user"
      end
    else
      redirect_to root_path, notice: "Failed to authenticate"
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_divider.html.haml
%h1.dash-divider - - - - - - - - - - 

app/views/application/_footer.html.haml
.page-footer
  =render 'divider'
  %p 
    &copy; Riley Spicer 2015 / 
    = link_to 'GitHub / ', 'http://www.github.com/rileyrileyrose' 
    = link_to "LinkedIn / ", "https://www.linkedin.com/in/rileyspicer"
    = link_to 'Twitter / ', 'https://twitter.com/rileyrileyrose'
    @rileyrileyrose

app/views/application/_google_analytics.html.erb
<% if Rails.env == "production"  %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-71562710-1', 'auto');
    ga('send', 'pageview');

  </script>
<% end %>

app/views/application/_navbar.html.haml
%nav.navbar.navbar-default
  .container
    .collapse.navbar-collapse#navbar
      %ul.nav.navbar-nav
        %li.navbar-left= link_to 'Home', root_path
        %li= link_to 'About Me', about_path
        / %li= link_to 'Blog', posts_path
        - if @current_user && @current_user.is_riley?
          %li= link_to 'Logout', logout_path
          %li= link_to 'Write Post', new_post_path
      %ul.nav.navbar-right

app/views/application/_post_form.html.haml
.row
  .col-sm-12.col-md-12.col-lg-12
    %h3 Write/Edit a Post
    .form
      = form_for @post do |p|
        %p
          Title: 
          = p.text_field :title, class: 'blog-title-field'
        %p
          Body: 
          = p.text_area :body, class: 'blog-body-field'
        %p
          = submit_tag "Submit"

/ Here's some lovely rules, in case I forget when writing up a post
.row
  %h3= link_to 'Textile Rules', 'http://redcloth.org/textile/writing-paragraph-text/'
  %ul
    %li h1. level 1 heading
    %li h2. level 2 heading
    %li h3. level 3 heading
    %li h4. level 4 heading

    %li \bq. this is blockquoted text

    %li \fn1. footnote 1
    %li \fn2. footnote 2
    %li \This text refernces a footnote[1]

    %li \# numbered list item 1
    %li \# numbered list item 2
    %li \* bulleted list first item
    %li \* bulleted list second item

    %li \_emphasis_
    %li \*strong*
    %li \??citation??
    %li \-deleted text-
    %li \+inserted text+
    %li \^superscript^
    %li \~subscript~
    %li \%span%

    %li \p(class). paragraph with a classname
    %li \p(#id). paragraph with an ID
    %li \p{color:red}. paragrah with a CSS style
    %li \p[fr]. paragraphe en français
    %li \p<. right aligned paragraph
    %li \p>. left aligned paragraph
    %li \p=. centered aligned paragraph
    %li \p<>. justified text paragraph

    %li \|_. head |_. table |_. row |
    %li \| a | table | row 1 |
    %li \| a | table | row 2 |

    %li \"linktext":url
    %li \!imageurl!

    %li \ABBR(Abbreviation)

app/views/application/_teeny_div.html.haml
%h3.small-dash-divider - - -

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Howdy, I'm Riley</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Special+Elite|Cutive+Mono' rel='stylesheet' type='text/css'>
  <%= render "google_analytics" %>
</head>
<body>

  <div class="container-fluid">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>

  <div class="container-fluid">
    <%= render 'navbar' %>
    <%= render 'divider' %>
    <%= yield :top_content %> 
    <h1><%= yield :header %></h1>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
<footer>
    <%= render 'footer' %>
</footer>
</html>

app/views/layouts/front-page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RileyCodes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Special+Elite|Cutive+Mono' rel='stylesheet' type='text/css'>
  <%= render "google_analytics" %>
</head>
<body>

  <div class="container-fluid">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>

  <div class="container-fluid">
    <%= yield :top_content %> 
    <h1><%= yield :header %></h1>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
<footer>
    <%= render 'footer' %>
</footer>
</html>

app/views/pages/about.html.haml
.row
  %h3
    I'm a software development engineer in Seattle, WA working at Amazon Web Services.
  = render "divider"
.row
  .col-sm-6.col-md-6
    .block
      %h3.left-header I like to:
      %ul 
        %li= link_to "knit lacy things", "www.ravelry.com/people/uniquechicstudio"
        %li 
          learn languages, both
          = link_to "computer", "https://github.com/rileyrileyrose"
          and 
          = link_to "human", "https://www.duolingo.com/rileyrileyrose"
        %li= link_to "write letters", "http://sendsomething.net"
        %li= link_to "play on aerial silks", "http://www.emeraldcitytrapeze.com/"
        %li= link_to "cook delicious food", "http://www.foodiewithfamily.com/classic-slow-cooker-cuban-pork-make-ahead-mondays-highlight/"
        %li= link_to "read poetry", "http://www.rjgeib.com/thoughts/geese/geese.html"
        %li= link_to "climb on things", "https://www.stonegardens.com/seattle/default.aspx"
  .col-sm-6.col-md-6
    %p
      After graduating
      = link_to "high school", "http://www.idyllwildarts.org/"
      as a creative writing major and spending four years at a
      = link_to "Great Books college", "http://www.sjc.edu/"
      developing a solid foundation in critical thinking and analysis, I traveled
      = link_to "around the US,", "https://www.google.com/search?q=homer,+alaska"
      meeting new people and growing in
      = link_to "diverse communities.", "https://www.google.com/search?q=hood+river+oregon"
    %p
      I've long dabbled in basic web development and computer science, and in 2015, I started my computer science journey at
      = link_to "Ada Developer's Academy.", "http://adadevelopersacademy.org/" 
      I moved on to work as a software development engineer (SDE) at
      = link_to "AWS,", "https://aws.amazon.com"
      where I work across our full stack to provide 
      = link_to "Budgeting", "https://aws.amazon.com" 
      features to our customers.
    %p 
      Currently interested in the challenges of scaling large systems efficiently and distributed computing. 

app/views/pages/haml_about.html.haml
.row
  %h1.test About Me
  %h4
    I'm a junior web developer in Seattle, WA attending
    = link_to "Ada Developer's Academy", "http://adadevelopersacademy.org/"
  .divider
.row
  .col-xs-6.col-sm-6.col-md-6
    .text-block.currently-playing
      %h3 Currently playing with:
      = link_to "Learn Node.js", "https://github.com/rileyrileyrose/learnNode"
    .block
      %h3.left-header I like to:
      %ul 
        %li= link_to "knit lacy things", "www.ravelry.com/people/uniquechicstudio"
        %li 
          learn languages, both
          = link_to "computer", "https://github.com/rileyrileyrose"
          and 
          = link_to "human", "https://www.duolingo.com/rileyrileyrose"
        %li= link_to "write letters", "http://sendsomething.net"
        %li= link_to "practice yoga", "http://www.flowhoodriver.com/"
        %li= link_to "cook delicious food", "http://www.foodiewithfamily.com/classic-slow-cooker-cuban-pork-make-ahead-mondays-highlight/"
        %li= link_to "read poetry", "http://www.rjgeib.com/thoughts/geese/geese.html"
  .col-xs-6.col-sm-6.col-md-6
    %p
      After graduating
      = link_to "high school", "http://www.idyllwildarts.org/"
      as a creative writing major, and spending four years at a
      = link_to "Great Books college", "http://www.sjc.edu/"
      developing a solid foundation in critical thinking and the development of Western Thought, I spent some time traveling
      = link_to "around the US", "https://www.google.com/search?q=homer,+alaska"
      , meeting new people and growing in
      = link_to "diverse communities.", "https://www.google.com/search?q=hood+river+oregon"
    %p
      I've long dabbled in web development and computer science, and in the fall of 2015, I started at
      = link_to "Ada Developer's Academy", "http://adadevelopersacademy.org/"
      where I'm growing and sharpening my skills as a web developer. At school, we complete
      = link_to "projects", projects_path
      sing Ruby, Rails, HTML, CSS, and Javascript. We use GitHub for all our projects, and regularly work on teams to get used to the git workflow and to hone our collaboration skills.
    %p 
      I look forward to using my 
      = link_to "newly developed skills", "http://github.com/rileyrileyrose"
      to work on technologies that improve the world around me.

app/views/pages/index.html.erb
<% content_for :top_content do %>
  <%= image_tag 'typewriter-greeting-no-period.jpg', class: 'img-responsive'  %>
<% end %>
<div class='row'>
  <div class="col-xs-12">
    <div class='front-page-text'>
      I'm an SDE at Amazon AWS where I work on the Billing Console team to better 
      the customer experience around interacting with their bill.
    </div>
  </div>
</div>
<div class="divider"></div>
<div class="row">
  <div class="col-xs-12">
    <h2>
      <%= link_to "want to learn more about me?", about_path %>
    </h2>
    <h4 class="text-block">
      <%= link_to '(you know you wanna)', about_path %>
    </h4>
  </div>
</div>

app/views/pages/projects.html.haml
.row
  %h2 Nothing to see here, folks.
  = render 'divider'

app/views/pages/secret.html.erb
<% header "Secret!" %>

app/views/posts/edit.html.haml
=render "post_form"

app/views/posts/index.html.haml
.row
  .col-sm-12.col-md-12.col-lg-12
    #blog-container
      - if @posts.length == 0
        %h1 Awesome Blog Posts
        %p.text-center Coming soon!
      - @posts.each do |post|
        %h2.blog-header= post.title
        %h4.blog-time= post.created_at.strftime("%B %d, %Y")
        .blog-post= raw RedCloth.new(post.body).to_html

app/views/posts/new.html.haml
=render "post_form"

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>